import { Inter } from "next/font/google";
// import "@/styles/globals.css";
import "@/styles/main.scss"
import Nav from "../components/Nav";
import Footer from "../components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
    <body>
          <Nav />
          <main>
          {children}
          </main>
          <Footer/>
     
    </body>
  </html>
  );
}
